#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "NNOS must be ran as root."
    exit 1
fi

mkdir -p /var/nnos/binarystorage/
touch /var/nnos/binarystorage/installed >> /var/log/syslog

OPTION="$1"

if [ "$(cat /var/nnos/binarystorage/installed)" == "1" ]; then
    help() {
        echo "Usage: nnos:"
        echo "[--help]: Display help information for NNOS"
        echo "[--restart]: Restart NNOS, or your machine if needed"
        echo "By The Nathan Network, INC™. All rights reserved"
        exit 1
    }

    case "$OPTION" in
        --restart)
            reboot
            exit 1
            ;;
        --shutdown)
            poweroff
            exit 1
            ;;
        --help)
            help
            exit 1
            ;;
        -p)
            nnpm
            exit 0
            ;;
        --hello)
            toilet "hello!"
            ;;
        *)
            echo "Usage: nnos: <Command>"
            exit 1
            ;;
    esac
else
    case "$OPTION" in
        --install)
            echo "1" > /var/nnos/binarystorage/installed
            apt install apache2
            apt install toilet
            apt install python3
            apt install lolcat
            wget http://downloads.nathannetwork.com/m/nnos/nnpm/nnpm
            mv nnpm /bin/
            apt update
            apt upgrade
            mv "$0" /usr/bin/
            chmod +x $0
            echo "To use NNOS, call the $(basename $0) command anytime."
            exit 0
            ;;
        *)
            echo "NNOS is not installed. Use nnos --install to install NNOS"
            exit 1
            ;;
    esac
fi
exit 0
